const IncensePrayersSequence: string[] =[ 
Prefix.commonIncense+"EleysonImasComment&D=$copticFeasts.AnyDay", 
Prefix.commonIncense+"EleysonImas&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"OurFatherWhoArtInHeaven&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"InTheNameOfJesusOurLord&D=$copticFeasts.AnyDay", 
Prefix.commonIncense+"ThanksGivingPart1Comment&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"BlockShlil&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"BlockIriniPassi&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"ThanksGivingPart1&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"DiaconResponsePray&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"ThanksGivingPart2&D=$copticFeasts.AnyDay", 
Prefix.commonIncense+"PrayThatGodHaveMercyOnUs&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"ThanksGivingPart3&D=$copticFeasts.AnyDay", 
Prefix.commonIncense+"ThanksGivingPart3Comment&D=$copticFeasts.AnyDay", 
Prefix.commonIncense+"CymbalVersesPlaceHolder&D=$copticFeasts.AnyDay", 
Prefix.commonIncense+"Comment1&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"BlockShlil&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"BlockIriniPassi&D=$copticFeasts.AnyDay", 
Prefix.incenseVespers+"PriestLitaniesComment&D=$copticFeasts.AnyDay", 
Prefix.incenseDawn+"SickPrayerPart1&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"KyrieElieson&D=$copticFeasts.AnyDay", 
Prefix.incenseDawn+"SickPrayerPart2&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"KyrieElieson&D=$copticFeasts.AnyDay", 
Prefix.incenseDawn+"SickPrayerPart3&D=$copticFeasts.AnyDay", 
Prefix.incenseDawn+"TravelersPrayerPart1&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"KyrieElieson&D=$copticFeasts.AnyDay", 
Prefix.incenseDawn+"TravelersPrayerPart2&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"KyrieElieson&D=$copticFeasts.AnyDay", 
Prefix.incenseDawn+"SickPrayerPart3&D=$copticFeasts.AnyDay", 
Prefix.incenseDawn+"OblationsPrayerPart1&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"KyrieElieson&D=$copticFeasts.AnyDay", 
Prefix.incenseDawn+"OblationsPrayerPart2&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"KyrieElieson&D=$copticFeasts.AnyDay", 
Prefix.incenseDawn+"SickPrayerPart3&D=$copticFeasts.AnyDay", 
Prefix.incenseVespers+"DepartedPrayerPart1&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"KyrieElieson&D=$copticFeasts.AnyDay", 
Prefix.incenseVespers+"DepartedPrayerPart2&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"KyrieElieson&D=$copticFeasts.AnyDay", 
Prefix.incenseDawn+"SickPrayerPart3&D=$copticFeasts.AnyDay", 
Prefix.commonIncense+"DoxolgiesComment&D=$copticFeasts.AnyDay",
Prefix.commonPrayer+"AngelsPrayer&D=$copticFeasts.AnyDay", 
Prefix.incenseVespers+"LordKeepUsThisNightWithoutSin&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"HolyGodHolyPowerfulPart1&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"GloryToTheFatherTheSonAndTheSpirit&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"HolyGodHolyPowerfulPart2&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"OurFatherWhoArtInHeaven&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer + "WeSaluteYouMary&D=$copticFeasts.AnyDay", 
Prefix.commonIncense+"DoxologiesPlaceHolder&D=$copticFeasts.AnyDay",  
Prefix.commonPrayer+"WeExaltYouStMary&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"Creed&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"EfnotiNaynanPart1Comment&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"EfnotiNaynanPart1&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"EfnotiNaynanPart2&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"EfnotiNaynanPart3&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"EfnotiNaynanPart4&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"KyrieEliesonThreeTimes&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"BlockShlil&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"BlockIriniPassi&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"GospelPrayerPlaceHolder&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"OurFatherWhoArtInHeaven&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"GospelLitanyComment4&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"BlockInTheNameOfOurLord&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"GospelLitanyComment5&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"BlockIriniPassi&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"AbsolutionForTheSon&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"KyrieEliesonThreeTimes&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"ConcludingHymnPart1&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"OurFatherWhoArtInHeaven&D=$copticFeasts.AnyDay", 
Prefix.commonPrayer+"ConcludingHymnPart2&D=$copticFeasts.AnyDay", 
]
; //    this is the generic sequence of all prayers for incense dawn and incense vespers. The onClick function triggered by btnIncenseDawn and btnIncenseVespers, will remove what is irrelevant and add what needs to be added according to whether it is a Dawn or Vespers office
    
const GospelPrayersSequence: string[] = [Prefix.psalmResponse, Prefix.gospelMass + 'Psalm', Prefix.gospelMass + 'Gospel', Prefix.gospelResponse]; //This is the generic sequence for the prayers related to the lecture of the gospel at any liturgy (mass, incense office, etc.). The OnClick function triggered by the liturgy, adds the dates of the readings and of the psalm and gospel responses
    
const MassPrayersSequences = {
    //those are the sequences of the 'Baptized' mass prayers (starting from Reconciliation) for each mass
    MassUnbaptized: [
        Prefix.massCommon+"GloryAndHonor&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"HallelujahFayBiBi&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"HallelujahFayBiBiFast&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"BenedictionOfTheLambPart1&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"BenedictionOfTheLambPart2&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"BenedictionOfTheLambPart3&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"DiaconResponseOneIsTheHolyGodPart1&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"DiaconResponseOneIsTheHolyGodPart2&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"DiaconResponseOneIsTheHolyGodPart3&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"GloryToTheFatherTheSonAndTheSpirit&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"BlockShlil&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"BlockIriniPassi&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"ThanksGivingPart1&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"DiaconResponsePray&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"KyrieElieson&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"ThanksGivingPart2&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"PrayThatGodHaveMercyOnUs&D=$copticFeasts.AnyDay",
        Prefix.commonPrayer+"KyrieElieson&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"ThanksGivingPart3&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AbsolutionForTheFather&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"WeHaveBeenSavedWithYou&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"Tayshoury&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"Tishoury&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"ByTheIntercessionOfStMary&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"ByTheIntercessionOfStMichael&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"ByTheIntercessionOfTheArchangels&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"ByTheIntercessionOfTheApostles&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"ByTheIntercessionOfStMarc&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"ByTheIntercessionOfStSteven&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"ByTheIntercessionOfStGeorgeStTheodoreStPhilopatirStMina&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"ByTheIntercessionOfTodaySaints&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"IntercessionForPope&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"IntercessionForBishop&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"WeBowToYouJesusChrist&D=$copticFeasts.AnyDay", 
        Prefix.praxisResponse+"PraxisResponsePart1&D=$copticFeasts.AnyDay", 
        Prefix.praxisResponse+"PraxisResponsePart2&D=$copticFeasts.AnyDay", 
        Prefix.massCommon + 'ReadingsPlaceHolder&D=&D=$copticFeasts.AnyDay',
        Prefix.commonPrayer+"HolyGodHolyPowerfullPart1&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer + "GloryToTheFatherTheSonAndTheSpirit&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"HolyGodHolyPowerfullPart2&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"BlockShlil&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"BlockIriniPassi&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"GospelPrayerPlaceHolder&D=$copticFeasts.AnyDay",
        Prefix.commonPrayer+"Creed&D=$copticFeasts.AnyDay"
        ], //Those are the prayers of the 'Unbaptized Mass'
        MassCommonIntro:[
        Prefix.massCommon+"ReconciliationComment&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"BlockShlil&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"BlockIriniPassi&D=$copticFeasts.AnyDay"
        ], //the introduction of reconciliation for all masses
        MassStBasil: [
        Prefix.massStBasil+"ReconciliationPart1&D=$copticFeasts.AnyDay", 
        Prefix.massCommon + "AnaphoraPart1&D=$copticFeasts.AnyDay", 
        Prefix.massStBasil + "Agios&D=$copticFeasts.AnyDay", 
        Prefix.massStBasil+"InstitutionNarrative&D=$copticFeasts.AnyDay",  
        Prefix.massCommon + "AsWeAlsoCommemorateHisHolyPassionPart1&D=$copticFeasts.AnyDay", 
        ], //The sequence of prayers of St Basil Mass (starting from Reconciliation)
        MassStGregory: [
        Prefix.massStGregory+"ReconciliationPart1&D=$copticFeasts.AnyDay", 
        Prefix.massStGregory + "AnaphoraPart1&D=$copticFeasts.AnyDay", 
        Prefix.massStGregory+"Agios&D=$copticFeasts.AnyDay", 
        Prefix.massStGregory+"AsWeCommemorateYourHolyPassionPart1&D=$copticFeasts.AnyDay", 
        Prefix.massStGregory+"CallOfTheHolySpiritPart1&D=$copticFeasts.AnyDay", 
        Prefix.massStGregory + "LitaniesIntroduction&D=$copticFeasts.AnyDay",
        Prefix.massStGregory + "FractionIntroduction&D=$copticFeasts.AnyDay&C=Title"
        ], //The sequence of prayers of St Gregory Mass (starting from reconciliation)
        MassStCyril:[
        Prefix.massStCyril+"ReconciliationPart1&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"DiaconResponsePrayForTotalPeace&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"KyrieElieson&D=$copticFeasts.AnyDay", 
        Prefix.massStCyril+"ReconciliationPart2&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"DiaconResponseKissEachOther&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"SpasmosAdamShort&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AnaphoraComment1&D=$copticFeasts.AnyDay", 
        Prefix.massStBasil+"AnaphoraPart1&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"BlockIriniPassi&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AnaphoraComment2&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AnaphoraPart2&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AnaphoraComment3&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AnaphoraPart3&D=$copticFeasts.AnyDay", 
        Prefix.massStCyril+"Part4&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"DiaconResponseYouWhoAreSittingStand&D=$copticFeasts.AnyDay", 
        Prefix.massStCyril+"Part5&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"DiaconResponseLookToTheOrient&D=$copticFeasts.AnyDay", 
        Prefix.massStCyril+"Part6&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"DiaconResponseLetUsAttendAmen&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"SpasmosWatesShort&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"SpasmosComment&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AgiosComment1&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AgiosPart1&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AgiosComment2&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AgiosPart1&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AgiosComment3&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AgiosPart1&D=$copticFeasts.AnyDay", 
        Prefix.massStCyril+"Part4&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
        Prefix.massStCyril+"Part5&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
        Prefix.massStCyril+"Part6&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
        Prefix.massStCyril+"Part7&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AgiosComment8&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"InstitutionNarrativePart3&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AssemblyResponseWeBelieveThatThisIsTrueAmen&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AgiosComment9&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"InstitutionNarrativePart4&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AgiosComment10&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"PriestBenedictionHeThanked&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"PriestBenedictionHeBlessedIt&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"PriestBenedictionHeSanctifiedIt&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AssemblyResponseWeBelieveWeConfessWeGlorify&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AgiosComment11&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"InstitutionNarrativePart5&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AgiosComment12&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"InstitutionNarrativePart6&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AssemblyResponseThisIsReallyTrue&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AgiosComment13&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"InstitutionNarrativePart7&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AgiosComment14&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"PriestBenedictionHeThanked&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"PriestBenedictionHeBlessedIt&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"PriestBenedictionHeSanctifiedIt&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AssemblyResponseWeAlsoBelieveConfesseAndGlorify&D=$copticFeasts.AnyDay", 
        Prefix.massStBasil+"InstitutionNarrative10Comment&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"InstitutionNarrativePart8&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AssemblyResponseThisIsAlsoReallyTrue&D=$copticFeasts.AnyDay", 
        Prefix.massStBasil+"InstitutionNarrative11Comment&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"InstitutionNarrativePart9&D=$copticFeasts.AnyDay", 
        Prefix.massStBasil+"InstitutionNarrative12Comment&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"InstitutionNarrativePart10&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AssemblyResponseAmenAmenAmenWeProclaimYourDeath&D=$copticFeasts.AnyDay", 
        Prefix.massStCyril+"Part8&D=$copticFeasts.AnyDay", 
        Prefix.massStCyril+"AgiosPart15&D=$copticFeasts.AnyDay", 
        Prefix.massStCyril+"Part9&D=$copticFeasts.AnyDay", 
        Prefix.massStCyril+"AgiosPart16&D=$copticFeasts.AnyDay", 
        Prefix.massStCyril+"Part10&D=$copticFeasts.AnyDay", 
        Prefix.massStCyril+"Part10&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"DiaconResponseLetUsAttendAmen&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
        Prefix.massStCyril+"Part11&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"CallOfTheHolySpiritPart2&D=$copticFeasts.AnyDay", 
        Prefix.massCommon+"AssemblyResponseWeAlsoBelieve&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"BlockIriniPassi&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
        Prefix.massStCyril+"LitaniesIntroduction&D=$copticFeasts.AnyDay",
        ], // the sequence of prayers of St Cyril Mass (starting from Reconciliation)
        MassStJohn: [], // the sequence of prayers of St John Mass (tarting from Reconciliation)
        MassCallOfHolySpirit:[ 
            Prefix.massCommon + "CallOfTheHolySpiritPart1&D=$copticFeasts.AnyDay",
        ],
        MassLitanies: [ 
            Prefix.massCommon+"LitaniesIntroduction&D=$copticFeasts.AnyDay",  
            Prefix.massCommon + "SaintsCommemoration&D=$copticFeasts.AnyDay", 
            Prefix.massCommon+"CommemorationOfTheDeparted&D=$copticFeasts.AnyDay", 
            Prefix.massCommon+"FractionIntroduction&D=$copticFeasts.AnyDay", 
            Prefix.commonPrayer+"OurFatherWhoArtInHeaven&D=$copticFeasts.AnyDay", 
            Prefix.commonPrayer + "BlockInTheNameOfOurLord&D=$copticFeasts.AnyDay", 
            Prefix.massCommon+"PrayerForTheFather&D=$copticFeasts.AnyDay",
            Prefix.commonPrayer + "BlockIriniPassi&D=$copticFeasts.AnyDay", 
            Prefix.massCommon+"AbsolutionPrayerForTheFather&D=$copticFeasts.AnyDay",
            Prefix.massCommon + "ConfessionIntroduction&D=$copticFeasts.AnyDay", 
            Prefix.massCommon+"Confession&D=$copticFeasts.AnyDay", 
            Prefix.commonPrayer+"ZoksasiKyrie&D=$copticFeasts.AnyDay"
            ], //The litanies. They are common to all masses except 
        Communion: [
        Prefix.massCommon+"CommunionPsalm150&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"EndPart1&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"EndPart2&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"AssemblyResponseAmeenItWillBe&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"EndPart3&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"OurFatherWhoArtInHeaven&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"EndPart4&D=$copticFeasts.AnyDay", 
        Prefix.commonPrayer+"AssemblyResponseAndWithYourSoul&D=$copticFeasts.AnyDay", 
        ], //the sequence of prayers from 'Confession' until the end of the mass, it is common to all masses 
};    

let bookOfHours = {
    DawnPrayersArray: [],
    DawnPrayersSequence: [],
    ThirdHourPrayersArray: [],
    ThirdHourPrayersSequence: [],
    SixthHourPrayersArray: [],
    SixthHourPrayersSequence: [],
    NinethHourPrayersArray: [],
    NinethHourPrayersSequence: [],
    EleventhHourPrayersArray: [],
    EleventhHourPrayersSequence: [],
    TwelvethHourPrayersArray: [],
    TwelvethHourPrayersSequence: [],
};   